Kesco.Web.Mvc.SharedViews/Models/SearchEntity/ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Kesco.DataAccess;
using BLToolkit.DataAccess;
using System.Data;
using BLToolkit.Data;
using BLToolkit.Mapping;
using Kesco.ObjectModel;
using System.ComponentModel.DataAnnotations;

namespace Kesco.Web.Mvc.SharedViews.Models.SearchEntity
{
	/// <summary>
	/// 
	/// </summary>
	public class EntityDescription
	{
		[MapField("КодСущности")]
		public int EntityID { get; set; }

		[MapField("Сущность")]
		public string EntityName { get; set; }
	}

	/// <summary>
	/// 
	/// </summary>
	public class Entity : TrackableEntity<Entity, int>
	{
		[UIHint("UniqueID")]
		[MapField("КодСущности")]
		public override int ID { get; set; }

		[MapField("Сущность")]
		[UIHint("TextBox")]
		[Display(Name = "Сущность", Description="Имя сущности")]
		public string EntityName { get; set; }

		[MapField("Описание")]
		[UIHint("TwoLinesTextBox")]
		[StringLength(255)]
		[Display(Name = "Описание", Description = "Описание сущности")]
		public string Description { get; set; }

		[MapField("ТаблицаИлиПредставление")]
		[UIHint("TextBox")]
		[StringLength(64)]
		[Display(Name = "Имя таблицы", Description = "Имя таблицы или пердставления")]
		public string TableName { get; set; }

		[MapField("ПрефиксТаблицы")]
		[UIHint("TextBox")]
		[StringLength(64)]
		[Display(Name = "Префикс таблицы", Description = "Префикс таблицы для использования в запросах")]
		public string TablePrefix { get; set; }

		[MapField("КлючевоеПоле")]
		[UIHint("TextBox")]
		[StringLength(64)]
		[Display(Name = "Ключевое поле", Description = "Ключевое поле в таблице")]
		public string KeyField { get; set; }

		[MapField("СписокПолейВывода")]
		[UIHint("TwoLinesTextBox")]
		[StringLength(4000)]
		[Display(Name = "Список полей", Description = "Список полей для вывода")]
		public string OutputFieldList { get; set; }

		/// <summary>
		/// Gets the friendly name of the instance.
		/// </summary>
		/// <returns></returns>
		public override string GetInstanceFriendlyName()
		{
			return StringExtensions.Coalesco(EntityName, "#{0}".FormatWith(EntityName));
		}
	}

	/// <summary>
	/// 
	/// </summary>
	public class DataModel
	{
		public int EntityID { get; set; }

		public Entity Entity { get; set; }

		public DataModel()
		{
			Entity = Entity.CreateInstance();
		}
			 
	}

	/// <summary>
	/// 
	/// </summary>
	public class ViewModel : ViewModel<DataModel>
	{
		public List<EntityDescription> Entities { get; set; }

		protected Repository repository { get; set; }

		public ViewModel()
		{
			repository = new Repository();
			Entities = repository.GetEntityList();
			//var accessor = SearchAccessor.CreateInstance
			Model.EntityID = 1;
			Model.Entity = repository.GetEntity(Model.EntityID);
		}

		protected override void CreateSettings()
		{
			;
		}
	}

	/// <summary>
	/// 
	/// </summary>
	public class Repository
	{
		protected DbManager Database { get; private set; }

		public Repository()
		{
			Database = new DB();
		}

		public Entity GetEntity(int id)
		{
			return Database
				.SetCommand(@"
						SELECT * 
						FROM Сущности 
						WHERE КодСущности = @КодСущности",
						Database.Parameter("@КодСущности", id)
					)
				.ExecuteObject<Entity>(id);
		}

		public List<EntityDescription> GetEntityList()
		{
			var list = new List<EntityDescription>();
			Database
				.SetCommand("SELECT КодСущности, Сущность FROM Сущности ORDER BY Сущность")
				.ExecuteList<EntityDescription>(list);
			return list;
		}

	}

	/// <summary>
	/// 
	/// </summary>
	public class DB : Database
	{

		public DB() : base("DS_search") { }

		protected override IDbCommand OnInitCommand(IDbCommand command)
		{
			IDbCommand dbCommand = base.OnInitCommand(command);
			dbCommand.CommandTimeout = 30 * 3;
			return dbCommand;
		}

	}

}

Kesco.Web.Mvc.SharedViews/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web.Mvc;
using Kesco.Web.Mvc.SharedViews.Localization;
using Kesco.Web.Mvc.SharedViews.Models;

using System.Web;
using Kesco.Web.Mvc.Infrastructure;
using FluentValidation;
using Kesco.Web.Mvc.SharedViews.Models.Test;
using Kesco.DataAccess;
using System.Data;

namespace Kesco.Web.Mvc.SharedViews.Controllers
{
	/// <summary>
	/// 
	/// </summary>
	public class DefaultController : SharedValidationSupportedController<Models.Test.DataModel>
	{

		/// <summary>
		/// Indexes this instance.
		/// </summary>
		/// <returns></returns>
		public ActionResult ZvonilkaScript()
		{
			Response.Clear();
			Response.ContentType = "text/javascript";
			Response.Cache.SetAllowResponseInBrowserHistory(true);
			Response.Cache.SetExpires(DateTime.UtcNow.AddDays(365));
			Response.Cache.SetValidUntilExpires(true);
			Response.Cache.SetRevalidation(HttpCacheRevalidation.AllCaches);
			Response.Cache.SetCacheability(HttpCacheability.Private);
			
			
			return View();
		}

		/// <summary>
		/// Возвращает настройки культуры для приложения.
		/// </summary>
		/// <returns>Настройки культуры для приложения</returns>
		protected override CultureSettings GetCorporateCultureSettings()
		{
			return Configuration.AppSettings.Culture;
		}

		/// <summary>
		/// Indexes this instance.
		/// </summary>
		/// <returns></returns>
		public ActionResult Index()
		{
			IndexViewModel model = new IndexViewModel();
			return View(model);
		}

		/// <summary>
		/// Edits this instance.
		/// </summary>
		/// <returns></returns>
		public ActionResult Edit()
		{
			IndexViewModel model = new IndexViewModel();
			return View(model);
		}

		/// <summary>
		/// Выполняет диспетчеризацию команд.
		/// </summary>
		/// <param name="command">Команда</param>
		/// <param name="control">Идентификатор элемента управления на стороне клиента</param>
		/// <param name="model">Модель</param>
		/// <param name="result">Результат действия, если команда обработана, иначе null.</param>
		/// <returns>
		/// Возвращает истину, если команда обработана, иначе false
		/// </returns>
		protected override bool DoDispatch(string command, string control, Models.Test.DataModel model, out ActionResult result)
		{
			result = null;
			switch (command) {
				case "save":
					result = Save(model);
					break;	
			}
			return base.DoDispatch(command, control, model, out result);
		}

		/// <summary>
		/// Saves the specified dummy.
		/// </summary>
		/// <param name="dummy">The dummy.</param>
		/// <returns></returns>
		[HttpPost]
		public ActionResult Save(Models.Test.DataModel dummy)
		{
			try {
				// Проверяем состояние модели (валидность данных)
				if (ModelState.IsValid) {
					/*dummy.ChangedBy = UserContext.EmployeeInfo.ID;
					dummy.ChangedDate = DateTime.Now;
					Session["Dummy"] = dummy;*/
					return JsonModel(dummy, JsonRequestBehavior.AllowGet);
				} else {
					return JsonError("Ошибка в переданных данных", GetModelErrors(), JsonRequestBehavior.AllowGet);
				}
			} catch (Exception ex) {
				Kesco.Logging.Logger.WriteEx(ex);
				return JsonError("Ошибка сохранения документа"
						, new object[] { 
							new { ErrorMessage = ex.Message} }
						, JsonRequestBehavior.AllowGet);
			}
		}
        

		/// <summary>
		/// Makes the call.
		/// </summary>
		/// <param name="clientName">Name of the client.</param>
		/// <returns></returns>
		public ActionResult GetAvailablePhones(string clientName)
		{
			List<AvailablePhone> phones = TapiClient.GetClientPhoneNumbers(clientName);
			return JsonModel(new {
				phones = phones.Where(p => p.Outcoming)
			}, JsonRequestBehavior.AllowGet);
		}

		/// <summary>
		/// Makes the call.
		/// </summary>
		/// <param name="phone">The phone.</param>
		/// <param name="clientName">Name of the client.</param>
		/// <param name="targetPhone">The target phone.</param>
		/// <returns></returns>
        //public ActionResult MakeCall(string phone, int equipmentID, string clientName, string targetPhone)
        //{
        //    try {
        //        targetPhone = (targetPhone ?? "").Trim();
        //        //Regex regex = new Regex(@"[^\d ]+", RegexOptions.IgnoreCase | RegexOptions.ECMAScript | RegexOptions.CultureInvariant);
        //        //targetPhone = regex.Replace(targetPhone, @"");
        //        if (String.IsNullOrEmpty(targetPhone))
        //            throw new Exception(Kesco.Web.Mvc.SharedViews.Localization.Resources.MakeCall_PhoneNotSpecified);

        //        List<AvailablePhone> phones = TapiClient.GetClientPhoneNumbers(clientName);
        //        var phoneEntry = phones.FirstOrDefault(p =>
        //                p.PhoneNumber == phone
        //                && p.EquipmentID == equipmentID
        //                && p.Outcoming
        //            );
        //        if (phoneEntry == null) {
        //            throw new Exception(String.Format(Kesco.Web.Mvc.SharedViews.Localization.Resources.MakeCall_PhoneNotFound, phone));
        //        }
        //        int callID = 0;

        //        // если контакт начинается с +, то это международный номер
        //        // получим номер набора, 
        //        if (targetPhone.StartsWith("+")) {
        //            string[] dialDigits = targetPhone.Split(new char[] { ' ' });
        //            dialDigits[0] = TapiClient.GetPhoneNumberDialDigits(dialDigits[0].Substring(1), phoneEntry.PhoneStationCode);
        //            targetPhone = String.Join(" ", dialDigits);
        //        }

        //        if (phoneEntry.PhoneStationCode == 0) {
        //            callID = Kesco.Tasks.RunTask(() => {
        //                return Kesco.Zvonilka.Zvonilka.MakeIpCall(
        //                    phoneEntry.CTI,
        //                    phoneEntry.PhoneNumber,
        //                    phoneEntry.NetName,
        //                    targetPhone);
        //            }, TimeSpan.FromSeconds(30));
        //        } else {
        //            callID = Kesco.Tasks.RunTask(() => {
        //                return Kesco.Zvonilka.Zvonilka.MakeDigitalCall(phoneEntry.CTI
        //                    , phoneEntry.PhoneNumber
        //                    , targetPhone, !String.IsNullOrEmpty(phoneEntry.Slave));
        //            }, TimeSpan.FromSeconds(30));
        //        }
        //        return JsonModel(new {
        //            established = callID > 0,
        //            callInfo = new {
        //                CallID = callID,
        //                CalledPhone = targetPhone,
        //                CallingPhone = (String.IsNullOrEmpty(phoneEntry.Slave)) ? phoneEntry.PhoneNumber : phoneEntry.Slave,
        //                ConnectionState = -1
        //            },
        //            message = String.Format(Resources.MakeCall_Call, phone, targetPhone)
        //        }, JsonRequestBehavior.AllowGet);
        //    } catch (Exception ex) {
        //        Kesco.Logging.Logger.WriteEx(ex);
        //        return JsonError(ex.Message, ex.ToString(), JsonRequestBehavior.AllowGet);
        //    }

        //}

		/// <summary>
		/// Checks the call.
		/// </summary>
		/// <param name="callID">The call ID.</param>
		/// <param name="phone">The phone.</param>
		/// <param name="clientName">Name of the client.</param>
		/// <param name="targetPhone">The target phone.</param>
		/// <returns></returns>
        //public ActionResult CheckCall(int callID, string phone, int equipmentID, string clientName, string targetPhone)
        //{

        //    try {
        //        bool active = false;
        //        string msg = String.Empty;
        //        List<AvailablePhone> phones = TapiClient.GetClientPhoneNumbers(clientName);

        //        var phoneEntry = phones.FirstOrDefault(p =>
        //                p.PhoneNumber == phone
        //                && p.EquipmentID == equipmentID
        //                && p.Outcoming
        //            );
        //        if (phoneEntry == null) {
        //            throw new Exception(String.Format(Kesco.Web.Mvc.SharedViews.Localization.Resources.MakeCall_PhoneNotFound, phone));
        //        }

        //        Kesco.Zvonilka.CallState state;
        //        if (phoneEntry.PhoneStationCode == 0) {
        //            state = Kesco.Tasks.RunTask(() => {
        //                return Kesco.Zvonilka.Zvonilka.GetIPCallState(callID);
        //            }, TimeSpan.FromSeconds(30));
        //            active = state.ID > 0 && state.State >= 0;
        //            msg = GetCallStateDescription(state.State);
        //        } else {
        //            state = Kesco.Tasks.RunTask(() => {
        //                return Kesco.Zvonilka.Zvonilka.GetDigitalCallState(callID);
        //            }, TimeSpan.FromSeconds(30));
        //            active = state.ID > 0 && state.State >= 0;
        //            msg = GetCallStateDescription(state.State);
        //        }
        //        return JsonModel(
        //            new {
        //                callInfo = new {
        //                    CallID = state.ID,
        //                    CalledPhone = state.AnsweredNumber,
        //                    CallingPhone = (String.IsNullOrEmpty(phoneEntry.Slave)) ? phoneEntry.PhoneNumber : phoneEntry.Slave,
        //                    ConnectionState = state.State
        //                },
        //                active = active,
        //                message = msg
        //            }, JsonRequestBehavior.AllowGet);
        //    } catch (Exception ex) {
        //        Kesco.Logging.Logger.WriteEx(ex);
        //        return JsonError(ex.Message, ex.ToString(), JsonRequestBehavior.AllowGet);
        //    }
        //}

		/// <summary>
		/// Cancel the call.
		/// </summary>
		/// <param name="callID">The call ID.</param>

Kesco.Web.Mvc.SharedViews/Controllers/ScriptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Reflection;
using System.Globalization;
using System.Threading;

namespace Kesco.Web.Mvc.SharedViews.Controllers
{
	/// <summary>
	/// Контроллер, действия которого возвращают кешируемые скрипты.
	/// </summary>
	public class ScriptController : CorporateCultureController
    {

		public ScriptController()
			: base()
		{
			UseCompressHtml = true;
			MimeTypesToCompress = new string[] { "text/javascript", "text/html" };
		}

		/// <summary>
		/// Возвращает скрипт, который определяет переменные окружения с локализованными строками для приложения.
		/// </summary>
		/// <param name="hash">The hash.</param>
		/// <returns>скрипт, который определяет переменные окружения с локализованными строками для приложения</returns>
		[ETagBasedCacheFilter("text/javascript", 
			ETagDependencies.ConfigurationDependency 
			| ETagDependencies.AssemblyDependency 
			| ETagDependencies.CultureDependency)]
		public ActionResult AppEnv(string hash)
		{
			return View("AppEnv");
		}

		/// <summary>
		/// Возвращает общий скрипт, который используется всеми приложениями.
		/// </summary>
		/// <param name="hash">The hash.</param>
		/// <returns>общий скрипт, который используется всеми приложениями</returns>
		[ETagBasedCacheFilter("text/javascript", ETagDependencies.AssemblyDependency)]
		public ActionResult AppCommon(string hash)
        {
			return View();
        }

		/// <summary>
		/// Возвращает скрипт, который обслуживает кнопку выбора темы приложения.
		/// </summary>
		/// <param name="hash">The hash.</param>
		/// <returns>Скрипт, который обслуживает кнопку выбора темы приложения</returns>
		[ETagBasedCacheFilter("text/javascript", ETagDependencies.AssemblyDependency)]
		public ActionResult AppThemeRoller(string hash)
		{
			return View();
		}

		/// <summary>
		/// Возвращает настройки корпоративной культуры.
		/// </summary>
		/// <returns>
		/// Настройки корпоративной культуры
		/// </returns>
		protected override CultureSettings GetCorporateCultureSettings()
		{
			return Configuration.AppSettings.Culture;
		}


    }
}

Kesco.Web.Mvc.SharedViews/Views/Default/DumpAssemblies.cshtml
@inherits Kesco.Web.Mvc.SharedViews.SharedViewPage<Kesco.Web.Mvc.SharedViews.Models.Dump.ViewModel>
@using Kesco.Web.Mvc
@{
	ViewBag.Title = "Страница для тестирования";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="overflow:auto;">
	<h2>Список загруженных сборок</h2>
	@foreach (var asm in Model.Model.Assemblies) {
    <div>@(asm.FullName) (@asm.ImageRuntimeVersion)</div>
	}
</div>

Kesco.Web.Mvc.SharedViews/Views/Default/Edit.cshtml
@inherits Kesco.Web.Mvc.SharedViews.SharedViewPage<Kesco.Web.Mvc.SharedViews.Models.IndexViewModel>
@{
    ViewBag.Title = "Редактирование документа";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="@(ViewData.TemplateInfo.HtmlFieldPrefix)__Container" style="overflow: auto;">
@using (Html.BeginForm("Save", null, FormMethod.Post, new { id = ViewData.TemplateInfo.HtmlFieldPrefix+"__Form"}))
{
	Html.EnableClientValidation();
    @Html.EditorFor(x => x.Model)
	<hr />
	<button type="submit" id="@(ViewData.TemplateInfo.HtmlFieldPrefix)__Submit" style="display: none;" >Сохранить</button>
	<script type="text/javascript">

		window.handleRequest_Dummy_ResponsibleEmployeePhone = function(request) {
			request.employeeID = ViewModel.Model.ResponsibleEmployeeID();
		}

		window.handleRequest_Dummy_ResponsibleEmployeeEmail = function(request) {
			request.employeeID = ViewModel.Model.ResponsibleEmployeeID();
		}

		window.handleRequest_Dummy_ResponsibleEmployeeMsn = function(request) {
			request.employeeID = ViewModel.Model.ResponsibleEmployeeID();
		}

		function dispatchCommand_Dummy_ResponsibleID(command) {
			dispatchCommand_EmployeeControl("Dummy_ResponsibleID", command)
		}

		function dispatchCommand_Dummy_SignedBy(command) {
			dispatchCommand_EmployeeControl("Dummy_SignedBy", command)
		}

		function dispatchCommand_EmployeeControl(controlID, command) {
			var $lookup = $("#"+controlID);
			var url; 
			var callbackUrl = encodeURIComponent('@(Url.FullPathAction("DialogResult", "Default"))');
			var item = $lookup.selectBox("getValue");
			switch(command) {
				case 'advSearch':
					if (window.console) console.log("advSearch", item);
					url = "@(Configuration.AppSettings.URI_user_search)?return=1&clid=62&mvc=1&callbackKey=c1&callbackUrl={0}&search={1}";
					url = $.validator.format(url, callbackUrl, encodeURIComponent(item.label));
					openPopupWindow(url, null, function(result) {
							if (result) {
								var item = $.isArray(result) ? result[0] : result;
								$lookup.selectBox("setValue", item);
							}
						}, 'EmployeeLookup', 800, 600, { centerScreen: 1 });
					return false;
					break;
				case 'view':
					url = '@(Configuration.AppSettings.URI_user_form)?id={0}';
					url = $.validator.format(url, "" + item.value);
					openPopupWindow(url, null, null, 'wndPerson_' + controlID, 800, 600, { close: false });
					break;
				default:
					break;
			}
		}	
	</script>
}
</div>

<script type="text/javascript" language="javascript">
	$(function () {
		@* 
			Обработчик события изменения размера окна 
		*@
		$(window).resize(function() {
			var $parent = $("#dialogContentPane");
			$("#@(ViewData.TemplateInfo.HtmlFieldPrefix)__Container").width($parent.width())
			$("#@(ViewData.TemplateInfo.HtmlFieldPrefix)__Container").height($parent.height())
		});

		$("#@(ViewData.TemplateInfo.HtmlFieldPrefix)__Form").submit(function () {
			if ($(this).valid()) { // Проверка валидности формы
				$.ajax({ // выполнить  Ajax запрос
					url: this.action,
					type: "POST",
					dataType: "json",
					data: ko.toJSON({
                        Model: ko.mapping.toJS(ViewModel.Model)
                    }),
					contentType: 'application/json; charset-utf8',
					success: function (response) {
						if (response.status == "ok") {
							window.location = "@(Url.Action("Index", "Default"))";
							return;
						}
						if (response.status == "error") {
							ajaxError(response.error.Content || response.error, response.error_details.Errors || response.error_details);
							return;
						}
					}
				});
			}
			return false;
		});

		ViewModel.Model.ResponsibleEmployeeID.subscribe(function(newValue) {
			if (!newValue) {
				$("#Model_ResponsibleEmployeePhone").selectBox("setValue", { value: "", label: ""});
				$("#Model_ResponsibleEmployeeEmail").selectBox("setValue", { value: "", label: ""});
				$("#Model_ResponsibleEmployeeMsn").selectBox("setValue", { value: "", label: ""});
			}
		});

	});

	function ajaxError(errMsg, errDetails) {
		var errDetails2 = "<ul>";
		$.map(errDetails, function(item, index) {
				if (item) {
					if (item.ErrorMessage) {
						errDetails2 += "<li>"+(item.ErrorMessage || item.Exception.Message)+"</li>";
					} else if (item.Errors) {
						$.map(item.Errors, function(err) {
							errDetails2 += "<li>"+(err.ErrorMessage || err.Exception.Message)+"</li>";
						});
					}
				}
			});
		errDetails2 += "</ul>";
		alertMessage("Ошибка приложения N1", ""+errMsg+""+errDetails2+"", "OK");
	}

</script>

@section Header {
    <button type="button" data-bind="jqueryui: { widget: 'button', options: { icons: { primary: 'ui-icon-disk' } }}, 
		click: function() {
			$('#@(ViewData.TemplateInfo.HtmlFieldPrefix)__Submit').click();
		}
		" >Сохранить</button>
&nbsp;
}

@section Footer {
	@Html.DisplayFor(m => m.Model,"ChangedByInfo")
	&nbsp;
}

Kesco.Web.Mvc.SharedViews/Views/Default/Index.cshtml
@inherits Kesco.Web.Mvc.SharedViews.SharedViewPage<Kesco.Web.Mvc.SharedViews.Models.IndexViewModel>
@{
    ViewBag.Title = "Просмотр документа";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div  id="@(ViewData.TemplateInfo.HtmlFieldPrefix)__Container" style="overflow: auto;">
@Html.DisplayFor(x => x.Model)
<hr />
<a id="MMM" href="javascript: void(0)" onclick="ViewModel.showPerson(1603)" data-bind="
		dynamicLink: {
			value: 1603,
			source: '/mvc/persons/personselect.aspx/getitem',
			tooltipSource: '/mvc/persons/personselect.aspx/personinfo/0'
		}
	"></a>
</div>

<script type="text/javascript" language="javascript">
	$(function () {
		@* 
			Обработчик события изменения размера окна 
		*@
		$(window).resize(function() {
			var $parent = $("#dialogContentPane");
			$("#@(ViewData.TemplateInfo.HtmlFieldPrefix)__Container").width($parent.width())
			$("#@(ViewData.TemplateInfo.HtmlFieldPrefix)__Container").height($parent.height())
		});


	});
</script>

@section Header {
	@Html.ActionLink("Редактировать", "Edit", "Default", new {  data_bind="jqueryui: { widget: 'button', options: { icons: { primary: 'ui-icon-pencil' } }}" } )
}


@section Footer {
	@Html.DisplayFor(m => m.Model, "ChangedByInfo")
	<br />
}

Kesco.Web.Mvc.SharedViews/Views/Default/Test.cshtml
@inherits Kesco.Web.Mvc.SharedViews.SharedViewPage<ViewModel>
@using Kesco.Web.Mvc
@using Kesco.Web.Mvc.Validation
@using Kesco.Web.Mvc.SharedViews.Models.Test
@{
    ViewBag.Title = "Страница для тестирования";
    Layout = "~/Views/Shared/_Layout.cshtml";

    Html.PrepareValidationFor();

    //Html.RegisterExternalScript("ScriptController_UserScriptHub", Url.Action("UserScriptHub", "Script"));  
}

@section Header {
	@*<script>
	    window.ViewModel.validate = function () {
	        $.ajax({
	            url: '@(Url.Action("Dispatch"))',
	            type: 'POST',
	            data: window.ko.toJSON({
	                command : "validate",
	                control : null,
	                model : { Model: window.ko.mapping.toJS(window.ViewModel.Model) }
	            }),
	            contentType: "application/json; charset=utf-8"
	        });
	    };
        

	</script>  *@  
}

@section Footer {  

}

@using (Html.BeginForm("Test", null, FormMethod.Post, new { id = ViewData.TemplateInfo.HtmlFieldPrefix + "__Form" }))
{
	@*table>
	<tr>
		<td>@Html.LabelFor(m => m.HttpAddress)</td>
		<td>@Html.DisplayFor(m => m.HttpAddress)</td>
	</tr>
	
	<tr>
		<td>@Html.LabelFor(m => m.DocumentInstance.ResponsibleEmployeeID)</td>
		<td>@Html.DisplayForEmployee("DocumentInstance.ResponsibleEmployeeID", EmployeeInfoTypes.FullName)</td>
	</tr>
	<tr>
		<td>@Html.LabelFor(m => m.DocumentInstance.ShipperID)</td>
		<td>@Html.DisplayForPerson("DocumentInstance.ShipperID", PersonInfoTypes.Nickname)</td>
	</tr>
	<tr>
		<td>@Html.LabelFor(m => m.DocumentInstance.ConsigneeID)</td>
		<td>@Html.DisplayForPerson("DocumentInstance.ConsigneeID", PersonInfoTypes.Nickname)</td>
	</tr>
	

	</table>*@

	
    
    

	<table width="100%">
		<tr><td></td><td>@Html.ValidationMessagesFor("ValidationResultsAll")</td></tr>
		<tr>
			<td width="135px;">@Html.LabelFor(m => m.Model.PersonID)</td>
			<td>@Html.EditorFor(m => m.Model.PersonID)</td>
		</tr>
		<tr><td></td><td>@Html.ValidationMessagesFor("ValidationResults")</td></tr>
    
		<tr>
			<td>@Html.LabelFor(m => m.Model.EmployeeID)</td>
			<td>@Html.EditorFor(m => m.Model.EmployeeID)</td>
		</tr>
        <tr><td></td><td>@Html.ValidationMessagesFor("ValidationResultsNext")</td></tr>
	</table>
	<button id="@(ViewData.TemplateInfo.HtmlFieldPrefix)__Submit" onclick="window.ViewModel.validate(); return false;">Проверить</button>
    @*foreach (var person in Model.PersonList)
    {
		<div>@person.Nickname</div>
    }*@

	
}